
spring:
  datasource:
#    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:TestH2DB
    username: sa
    password: password

  h2:
    console:
      enabled: 'true'

  jpa:
    hibernate:
      ddl-auto: create-drop
#      ddl-auto: validate

    show-sql: true
    defer-datasource-initialization: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect

  sql:
     init:
      mode: always

server:
  port: 8080
